### ISSUE TITLE
Volume UI

### ISSUE THREAD

**Issue by jhauns** [pecinko/quartz#42]
Hello, I want first to say I love the most recent versions of Quartz It is the only theme I have used for years. Thanks for the effort in building and continuing to improve it.

I have one suggestion:

The volume up/down UI action currently works similar to OSX, where a large volume level indicator icon appears in the middle of the screen and slowly fades away. I find that this can be overly distracting while watching video. I think it would be worth experimenting with this element so that it is simpler and discreet in placement, so it would be less interruptive and consistent with the overall look of the theme as it is currently.

Thank you again.

**Comment by pecinko** [comment]
updated
